services:
  bankcards-app:
    build:
      context: .
      dockerfile: Docker.prod  
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/banksCards
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256

    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - bankcards-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=banksCards
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - bankcards-network

volumes:
  postgres_data:

networks:
  bankcards-network:
    driver: bridge
